In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr[4]

5

In [4]:
# Slicing
# 0 - Include
# 5 - Excluded
print(arr[0:5])

[1 2 3 4 5]


In [5]:
print(arr[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [6]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9,10,'Hello', 'Bye'])

In [7]:
print(arr_1)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' 'Hello' 'Bye']


In [9]:
arr.max()

10

In [10]:
arr.min()

1

In [11]:
arr.shape

(10,)

In [12]:
arr_2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr_2.shape

(3, 3)

In [14]:
arr_2.ndim

2

In [30]:
x = np.ndarray([5,3])

In [31]:
x

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
x.ndim

2

In [35]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [36]:
np.zeros([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [39]:
np.random.random(5) * 100

array([ 40.04336057,  42.81742452,  30.66451376,  67.27863004,  12.90833646])

In [43]:
np.random.randint(5,10)

9

In [44]:
x = np.zeros([5,5])

In [45]:
x.ndim

2

In [46]:
x.ravel()

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])